version: '3.8'

services:
  planify-api-app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - planify-api-mongo
    environment:
      - MONGODB_URI=mongodb://planify-api-mongo:27017/planify

  planify-api-mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

