databaseChangeLog:
  - changeSet:
      id: 4
      author: cicera_ribeiro
      changes:
        - createTable:
            tableName: services
            columns:
              - column:
                  name: id
                  type: BIGSERIAL
                  constraints:
                    primaryKey: true
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: TEXT
              - column:
                  name: price
                  type: NUMERIC(10,2)
              - column:
                  name: duration
                  type: INT
              - column:
                  name: category
                  type: VARCHAR(100)
              - column:
                  name: owner_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP